// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.0
// source: rpc/epicstorecommunicator/service.proto

package epicstorecommunicator

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EmptyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_epicstorecommunicator_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_epicstorecommunicator_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_rpc_epicstorecommunicator_service_proto_rawDescGZIP(), []int{0}
}

type EpicStoreGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl     string `protobuf:"bytes,2,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	PromoEndDate string `protobuf:"bytes,3,opt,name=promoEndDate,proto3" json:"promoEndDate,omitempty"`
}

func (x *EpicStoreGame) Reset() {
	*x = EpicStoreGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_epicstorecommunicator_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EpicStoreGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpicStoreGame) ProtoMessage() {}

func (x *EpicStoreGame) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_epicstorecommunicator_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpicStoreGame.ProtoReflect.Descriptor instead.
func (*EpicStoreGame) Descriptor() ([]byte, []int) {
	return file_rpc_epicstorecommunicator_service_proto_rawDescGZIP(), []int{1}
}

func (x *EpicStoreGame) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EpicStoreGame) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *EpicStoreGame) GetPromoEndDate() string {
	if x != nil {
		return x.PromoEndDate
	}
	return ""
}

type FreeEpicStoreGamesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Games []*EpicStoreGame `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
}

func (x *FreeEpicStoreGamesResp) Reset() {
	*x = FreeEpicStoreGamesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_epicstorecommunicator_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreeEpicStoreGamesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeEpicStoreGamesResp) ProtoMessage() {}

func (x *FreeEpicStoreGamesResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_epicstorecommunicator_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeEpicStoreGamesResp.ProtoReflect.Descriptor instead.
func (*FreeEpicStoreGamesResp) Descriptor() ([]byte, []int) {
	return file_rpc_epicstorecommunicator_service_proto_rawDescGZIP(), []int{2}
}

func (x *FreeEpicStoreGamesResp) GetGames() []*EpicStoreGame {
	if x != nil {
		return x.Games
	}
	return nil
}

type IsAliveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *IsAliveResp) Reset() {
	*x = IsAliveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_epicstorecommunicator_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsAliveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAliveResp) ProtoMessage() {}

func (x *IsAliveResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_epicstorecommunicator_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAliveResp.ProtoReflect.Descriptor instead.
func (*IsAliveResp) Descriptor() ([]byte, []int) {
	return file_rpc_epicstorecommunicator_service_proto_rawDescGZIP(), []int{3}
}

func (x *IsAliveResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_rpc_epicstorecommunicator_service_proto protoreflect.FileDescriptor

var file_rpc_epicstorecommunicator_service_proto_rawDesc = []byte{
	0x0a, 0x27, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x70, 0x69, 0x63, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x27, 0x64, 0x65, 0x6e, 0x6e, 0x69,
	0x73, 0x73, 0x73, 0x64, 0x65, 0x76, 0x2e, 0x79, 0x6f, 0x69, 0x6e, 0x6b, 0x2e, 0x65, 0x70, 0x69,
	0x63, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x22, 0x0a, 0x0a, 0x08, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x22, 0x63,
	0x0a, 0x0d, 0x45, 0x70, 0x69, 0x63, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12,
	0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x45, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x45, 0x6e, 0x64, 0x44,
	0x61, 0x74, 0x65, 0x22, 0x66, 0x0a, 0x16, 0x46, 0x72, 0x65, 0x65, 0x45, 0x70, 0x69, 0x63, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4c, 0x0a,
	0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x64,
	0x65, 0x6e, 0x6e, 0x69, 0x73, 0x73, 0x73, 0x64, 0x65, 0x76, 0x2e, 0x79, 0x6f, 0x69, 0x6e, 0x6b,
	0x2e, 0x65, 0x70, 0x69, 0x63, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x45, 0x70, 0x69, 0x63, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x25, 0x0a, 0x0b, 0x49,
	0x73, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x32, 0x94, 0x02, 0x0a, 0x15, 0x45, 0x70, 0x69, 0x63, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x86, 0x01, 0x0a,
	0x10, 0x50, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x46, 0x72, 0x65, 0x65, 0x47, 0x61, 0x6d, 0x65,
	0x73, 0x12, 0x31, 0x2e, 0x64, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x73, 0x73, 0x64, 0x65, 0x76, 0x2e,
	0x79, 0x6f, 0x69, 0x6e, 0x6b, 0x2e, 0x65, 0x70, 0x69, 0x63, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x1a, 0x3f, 0x2e, 0x64, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x73, 0x73, 0x64,
	0x65, 0x76, 0x2e, 0x79, 0x6f, 0x69, 0x6e, 0x6b, 0x2e, 0x65, 0x70, 0x69, 0x63, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x46,
	0x72, 0x65, 0x65, 0x45, 0x70, 0x69, 0x63, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x47, 0x61, 0x6d, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x72, 0x0a, 0x07, 0x49, 0x73, 0x41, 0x6c, 0x69, 0x76, 0x65,
	0x12, 0x31, 0x2e, 0x64, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x73, 0x73, 0x64, 0x65, 0x76, 0x2e, 0x79,
	0x6f, 0x69, 0x6e, 0x6b, 0x2e, 0x65, 0x70, 0x69, 0x63, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x1a, 0x34, 0x2e, 0x64, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x73, 0x73, 0x64, 0x65,
	0x76, 0x2e, 0x79, 0x6f, 0x69, 0x6e, 0x6b, 0x2e, 0x65, 0x70, 0x69, 0x63, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x73,
	0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x1b, 0x5a, 0x19, 0x72, 0x70, 0x63,
	0x2f, 0x65, 0x70, 0x69, 0x63, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_epicstorecommunicator_service_proto_rawDescOnce sync.Once
	file_rpc_epicstorecommunicator_service_proto_rawDescData = file_rpc_epicstorecommunicator_service_proto_rawDesc
)

func file_rpc_epicstorecommunicator_service_proto_rawDescGZIP() []byte {
	file_rpc_epicstorecommunicator_service_proto_rawDescOnce.Do(func() {
		file_rpc_epicstorecommunicator_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_epicstorecommunicator_service_proto_rawDescData)
	})
	return file_rpc_epicstorecommunicator_service_proto_rawDescData
}

var file_rpc_epicstorecommunicator_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_epicstorecommunicator_service_proto_goTypes = []interface{}{
	(*EmptyReq)(nil),               // 0: dennisssdev.yoink.epicstorecommunicator.EmptyReq
	(*EpicStoreGame)(nil),          // 1: dennisssdev.yoink.epicstorecommunicator.EpicStoreGame
	(*FreeEpicStoreGamesResp)(nil), // 2: dennisssdev.yoink.epicstorecommunicator.FreeEpicStoreGamesResp
	(*IsAliveResp)(nil),            // 3: dennisssdev.yoink.epicstorecommunicator.IsAliveResp
}
var file_rpc_epicstorecommunicator_service_proto_depIdxs = []int32{
	1, // 0: dennisssdev.yoink.epicstorecommunicator.FreeEpicStoreGamesResp.games:type_name -> dennisssdev.yoink.epicstorecommunicator.EpicStoreGame
	0, // 1: dennisssdev.yoink.epicstorecommunicator.EpicStoreCommunicator.PingForFreeGames:input_type -> dennisssdev.yoink.epicstorecommunicator.EmptyReq
	0, // 2: dennisssdev.yoink.epicstorecommunicator.EpicStoreCommunicator.IsAlive:input_type -> dennisssdev.yoink.epicstorecommunicator.EmptyReq
	2, // 3: dennisssdev.yoink.epicstorecommunicator.EpicStoreCommunicator.PingForFreeGames:output_type -> dennisssdev.yoink.epicstorecommunicator.FreeEpicStoreGamesResp
	3, // 4: dennisssdev.yoink.epicstorecommunicator.EpicStoreCommunicator.IsAlive:output_type -> dennisssdev.yoink.epicstorecommunicator.IsAliveResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_epicstorecommunicator_service_proto_init() }
func file_rpc_epicstorecommunicator_service_proto_init() {
	if File_rpc_epicstorecommunicator_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_epicstorecommunicator_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_epicstorecommunicator_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EpicStoreGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_epicstorecommunicator_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreeEpicStoreGamesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_epicstorecommunicator_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsAliveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_epicstorecommunicator_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_epicstorecommunicator_service_proto_goTypes,
		DependencyIndexes: file_rpc_epicstorecommunicator_service_proto_depIdxs,
		MessageInfos:      file_rpc_epicstorecommunicator_service_proto_msgTypes,
	}.Build()
	File_rpc_epicstorecommunicator_service_proto = out.File
	file_rpc_epicstorecommunicator_service_proto_rawDesc = nil
	file_rpc_epicstorecommunicator_service_proto_goTypes = nil
	file_rpc_epicstorecommunicator_service_proto_depIdxs = nil
}
