// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0-devel
// 	protoc        v3.12.0
// source: rpc/greeter/service.proto

package greeter

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NameInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // just enter your name here
}

func (x *NameInput) Reset() {
	*x = NameInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_greeter_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameInput) ProtoMessage() {}

func (x *NameInput) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_greeter_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameInput.ProtoReflect.Descriptor instead.
func (*NameInput) Descriptor() ([]byte, []int) {
	return file_rpc_greeter_service_proto_rawDescGZIP(), []int{0}
}

func (x *NameInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GreeterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *GreeterResponse) Reset() {
	*x = GreeterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_greeter_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreeterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreeterResponse) ProtoMessage() {}

func (x *GreeterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_greeter_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreeterResponse.ProtoReflect.Descriptor instead.
func (*GreeterResponse) Descriptor() ([]byte, []int) {
	return file_rpc_greeter_service_proto_rawDescGZIP(), []int{1}
}

func (x *GreeterResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_rpc_greeter_service_proto protoreflect.FileDescriptor

var file_rpc_greeter_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x74, 0x77, 0x69,
	0x72, 0x70, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x65, 0x72, 0x22, 0x1f, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x32, 0x63, 0x0a, 0x07, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x58, 0x0a, 0x0c, 0x4d, 0x61, 0x6b, 0x65, 0x47, 0x72, 0x65,
	0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x4e, 0x61,
	0x6d, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x26, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2e,
	0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x15, 0x5a, 0x13, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x3b, 0x67,
	0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_greeter_service_proto_rawDescOnce sync.Once
	file_rpc_greeter_service_proto_rawDescData = file_rpc_greeter_service_proto_rawDesc
)

func file_rpc_greeter_service_proto_rawDescGZIP() []byte {
	file_rpc_greeter_service_proto_rawDescOnce.Do(func() {
		file_rpc_greeter_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_greeter_service_proto_rawDescData)
	})
	return file_rpc_greeter_service_proto_rawDescData
}

var file_rpc_greeter_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_greeter_service_proto_goTypes = []interface{}{
	(*NameInput)(nil),       // 0: twirp.example.greeter.NameInput
	(*GreeterResponse)(nil), // 1: twirp.example.greeter.GreeterResponse
}
var file_rpc_greeter_service_proto_depIdxs = []int32{
	0, // 0: twirp.example.greeter.Greeter.MakeGreeting:input_type -> twirp.example.greeter.NameInput
	1, // 1: twirp.example.greeter.Greeter.MakeGreeting:output_type -> twirp.example.greeter.GreeterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_greeter_service_proto_init() }
func file_rpc_greeter_service_proto_init() {
	if File_rpc_greeter_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_greeter_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_greeter_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreeterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_greeter_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_greeter_service_proto_goTypes,
		DependencyIndexes: file_rpc_greeter_service_proto_depIdxs,
		MessageInfos:      file_rpc_greeter_service_proto_msgTypes,
	}.Build()
	File_rpc_greeter_service_proto = out.File
	file_rpc_greeter_service_proto_rawDesc = nil
	file_rpc_greeter_service_proto_goTypes = nil
	file_rpc_greeter_service_proto_depIdxs = nil
}
